Match terms case insensitively
rohberg/volto-slate-glossary pull request #4
Opened 2024-09-10 13:00 UTC by mauritsvanrees

And fix the regular expression to also work for umlauts at the beginning or end of a word.  This should work for other non-ascii characters as well.

I have this glossary for testing:

![Screenshot 2024-09-10 at 14 55 36](https://github.com/user-attachments/assets/8eda32b0-921c-41b3-bbf6-bb0ebe615148)

Initially with the main branch a test page looks like this:

![Screenshot 2024-09-10 at 14 34 52](https://github.com/user-attachments/assets/de7eba09-babd-44c6-a424-f48e75042b39)

Problem (for me) is that this only shows glossary items when the case matches.  This is fixed with the first commit:

![Screenshot 2024-09-10 at 14 34 59](https://github.com/user-attachments/assets/3b464373-5bd3-4cc5-af89-8847b4cee717)

Then I started looking at the support for accented characters, and found that it did not work if such a character was at the start or end of a term.  So I did another commit:

![Screenshot 2024-09-10 at 14 35 09](https://github.com/user-attachments/assets/6248adb9-6a8c-4ac3-87ce-e87c2abefbbc)

2024-09-11 08:12 UTC, ksuess commented
Thank you for the PR. The fix for the non-ascii characters on word/line start/end is fine.

The change to case insensitive match should be optional. For some abbreviations this would create unwanted matches. 
Example: For glossary term 'REST' (Representational State Transfer) this would match also the word 'rest' in 'The rest of the books are over there.'

2024-09-12 15:41 UTC, mauritsvanrees commented
Idea:

1. Make the case sensitivity matching optional using a config option.  Default: match all.
2. When the term is in all uppercase, only match words that are all uppercase.

I can work on that.

2024-09-12 17:55 UTC, mauritsvanrees commented
I have made both changes.
I have added `config.settings.glossary.case_sensitive`, with default value false.

I am not sure if that is the best place in the config to put it.  You have more experience with Volto, so I am happy to name it differently, or change the default.

2024-09-14 11:18 UTC, ksuess requested changes
That's fine. I think your solution with the insensitive match with exception of uppercase abbreviations is what fits most use cases.

Just a minor change request for a camel case name.

Thanks!

2024-09-14 11:18 UTC, ksuess commented on README.md
> +}
```suggestion
config.settings.glossary.caseSensitive = true;
```

2024-09-14 11:18 UTC, ksuess commented on src/index.js
> +  }
```suggestion
  config.settings.glossary = {
    caseSensitive: false,
  };
  config.settings.slate.leafs = {
    text: ({ children }) => <TextWithGlossaryTooltips text={children} />,
  };
```

2024-09-14 11:18 UTC, ksuess commented on src/utils.js
> +  const case_sensitive = config.settings.glossary.case_sensitive;
```suggestion
  const caseSensitive = config.settings.glossary.caseSensitive;
```

2024-09-14 11:18 UTC, ksuess commented on src/utils.js
> +          if (case_sensitive || term.term === term.term.toUpperCase()) {
```suggestion
          if (caseSensitive || term.term === term.term.toUpperCase()) {
```

2024-09-14 11:18 UTC, ksuess commented on README.md
> +Regardless of this setting, when you have a fully uppercase term, for example `REST` (REpresentational State Transfer), always only the exact word `REST` gets a tooltip, not `rest` or `Rest`.
```suggestion
Regardless of this setting, when you have a fully uppercase term, for example `REST` (Representational State Transfer), always only the exact word `REST` gets a tooltip, not `rest` or `Rest`.
```

2024-09-16 09:45 UTC, mauritsvanrees commented
Thanks for the review.  I have applied your suggestions, and tested again and it works.

2024-09-16 13:05 UTC, ksuess approved these changes

2024-09-16 13:15 UTC, merged